### ISSUE TITLE
Archetype allows a "name" attribute that is not allowed by engine when deploying the build theme

### ISSUE THREAD

**Issue by laurentleseigneur** [bonitasoft/bonita-theme-archetype#6]
**Describe the bug**
create a theme using
```
 mvn archetype:generate  \ 
-DarchetypeGroupId=org.bonitasoft.archetypes  \
-DarchetypeArtifactId=bonita-theme-archetype \
-DgroupId=com.bonitasoft.presales.theme \
-DartifactId=theme-presales-template \
-Dversion=0.0.1-SNAPSHOT \
-Dname=theme-presales-template \
-DdisplayName="Theme for presales BPM template"
```
this works fine and I am able to publish it to a private maven repo

**To Reproduce**
when I import in the studio, it it recognized as theme
when deploying, I got this exception from engine:
```
09-Feb-2022 15:44:17.591 AVERTISSEMENT [http-nio-8080-exec-6] org.bonitasoft.console.common.server.servlet.PageUploadServlet.getPermissionsError USERNAME=install | Page name is not valid, it must contains only alpha numeric characters and start with custompage_
09-Feb-2022 15:44:17.689 GRAVE [http-nio-8080-exec-8] org.bonitasoft.web.toolkit.server.servlet.ToolkitHttpServlet.catchAllExceptions org.bonitasoft.engine.exception.InvalidPageTokenException: USERNAME=install | Page name is not valid, it must contains only alpha numeric characters and start with custompage_
	org.bonitasoft.web.toolkit.client.common.exception.api.APIException: org.bonitasoft.engine.exception.InvalidPageTokenException: USERNAME=install | Page name is not valid, it must contains only alpha numeric characters and start with custompage_
		at org.bonitasoft.web.rest.server.datastore.page.PageDatastore.add(PageDatastore.java:136)
		at org.bonitasoft.web.rest.server.api.page.APIPage.add(APIPage.java:64)
		at org.bonitasoft.web.rest.server.api.page.APIPage.add(APIPage.java:44)
		at org.bonitasoft.web.rest.server.framework.API.runAdd(API.java:150)
		at org.bonitasoft.web.rest.server.framework.APIServletCall.doPost(APIServletCall.java:204)
		at org.bonitasoft.web.toolkit.server.servlet.ToolkitHttpServlet.doPost(ToolkitHttpServlet.java:211)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
		at org.bonitasoft.web.toolkit.server.servlet.ToolkitHttpServlet.service(ToolkitHttpServlet.java:72)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
		at org.bonitasoft.web.toolkit.server.servlet.ToolkitHttpServlet.service(ToolkitHttpServlet.java:249)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
		at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
		at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
		at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.AbstractAuthorizationFilter.doFilter(AbstractAuthorizationFilter.java:61)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.ContentTypeSecurityFilter.proceedWithFiltering(ContentTypeSecurityFilter.java:65)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:37)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.FrameSecurityFilter.proceedWithFiltering(FrameSecurityFilter.java:66)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:37)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.filter.NoCacheFilter.doFilter(NoCacheFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
		at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
		at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:385)
		at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)
		at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)
		at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
		at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
		at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
		at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.AbstractAuthorizationFilter.doFilter(AbstractAuthorizationFilter.java:61)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationRule.proceedWithRequest(AuthenticationRule.java:53)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.isAuthorized(AuthenticationFilter.java:132)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.doAuthenticationFiltering(AuthenticationFilter.java:107)
		at org.bonitasoft.console.common.server.login.filter.AuthenticationFilter.proceedWithFiltering(AuthenticationFilter.java:94)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:37)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.auth.impl.oidc.BonitaOIDCFilter.doFilter(BonitaOIDCFilter.java:127)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.AbstractAuthorizationFilter.doFilter(AbstractAuthorizationFilter.java:61)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.ContentTypeSecurityFilter.proceedWithFiltering(ContentTypeSecurityFilter.java:65)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:37)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.login.filter.FrameSecurityFilter.proceedWithFiltering(FrameSecurityFilter.java:66)
		at org.bonitasoft.console.common.server.filter.ExcludingPatternFilter.doFilter(ExcludingPatternFilter.java:37)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.bonitasoft.console.common.server.filter.NoCacheFilter.doFilter(NoCacheFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: org.bonitasoft.engine.exception.InvalidPageTokenException: USERNAME=install | Page name is not valid, it must contains only alpha numeric characters and start with custompage_
		at org.bonitasoft.engine.api.impl.page.PageAPIDelegate.createPage(PageAPIDelegate.java:165)
		at org.bonitasoft.engine.api.impl.PageAPIImpl.createPage(PageAPIImpl.java:95)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.bonitasoft.engine.api.impl.ServerAPIImpl.invokeAPI(ServerAPIImpl.java:430)
		at org.bonitasoft.engine.api.impl.ServerAPIImpl.lambda$invokeAPIInTransaction$1(ServerAPIImpl.java:398)
		at org.bonitasoft.engine.transaction.JTATransactionServiceImpl.executeInTransaction(JTATransactionServiceImpl.java:269)
		at org.bonitasoft.engine.api.impl.ServerAPIImpl.invokeAPIInTransaction(ServerAPIImpl.java:394)
		at org.bonitasoft.engine.api.impl.ServerAPIImpl.invokeAPI(ServerAPIImpl.java:268)
		at org.bonitasoft.engine.api.impl.ServerAPIImpl.invokeMethod(ServerAPIImpl.java:124)
		at org.bonitasoft.engine.api.impl.ClientInterceptor.invoke(ClientInterceptor.java:79)
		at com.sun.proxy.$Proxy139.createPage(Unknown Source)
		at org.bonitasoft.web.rest.server.datastore.page.PageDatastore.createEnginePage(PageDatastore.java:180)
		at org.bonitasoft.web.rest.server.datastore.page.PageDatastore.add(PageDatastore.java:126)
		... 88 more
	Caused by: org.bonitasoft.engine.page.SInvalidPageTokenException: Page name is not valid, it must contains only alpha numeric characters and start with custompage_
		at org.bonitasoft.engine.page.impl.PageServiceImpl.checkPageNameIsValid(PageServiceImpl.java:351)
		at org.bonitasoft.engine.page.impl.PageServiceImpl.readPageZip(PageServiceImpl.java:259)
		at org.bonitasoft.engine.page.impl.PageServiceImpl.buildPage(PageServiceImpl.java:221)
		at org.bonitasoft.engine.page.impl.PageServiceImpl.addPage(PageServiceImpl.java:190)
		at org.bonitasoft.engine.api.impl.page.PageAPIDelegate.createPage(PageAPIDelegate.java:161)
		... 103 more
```

due to the `-` in the Name

**Expected behavior**
This should be detected when building the theme

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: mac os
 - Version monterey

**Additional context**
studio 2012.2-u2

**Comment by rbioteau** [comment]
Resolved with https://github.com/bonitasoft/bonita-theme-archetype/commit/0b317f1d3704d5496983c902ea96520794ab0119
